/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import curveauto.Main;
import org.junit.Test;
import org.junit.experimental.categories.Category;

import static org.junit.Assert.*;

public class MainTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
